name: mix_annotations
description: Annotations for mix and mix_generator
version: 0.3.1
repository: https://github.com/conceptadev/mix

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  test: ^1.21.0
  dart_code_metrics_presets: ^2.14.0
  flutter_lints: ^4.0.0
