name: mix_generator
description: A code generator for Mix, an expressive way to effortlessly build design systems in Flutter.
version: 0.3.2
homepage: https://github.com/conceptadev/mix

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  mix_annotations: ^0.3.1
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.1.0
  dart_style: ^2.3.6
  collection: ^1.17.1
  build_config: ^1.1.1

dev_dependencies:
  test: ^1.24.4
  build_runner: ^2.4.9
  build_test: ^2.2.2
  source_gen_test: ^1.0.6
  # Lint
  dart_code_metrics_presets: ^2.14.0
  flutter_lints: ^4.0.0
